#!/bin/bash

_mod=${1:-perl-dependencies}
_req=${2:-perl-requirements.txt}

unset _perl_mods

while read -r line; do
  _perl_mods+=" $line"
done < $_req

flatpak-cpan-generator.pl --output ${_mod}-sources.json $_perl_mods
